# Generated by Django 5.2.7 on 2025-12-28 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0003_alter_profile_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, help_text="Student's date of birth", null=True)),
                ('address', models.TextField(blank=True, help_text='Full address', max_length=255)),
                ('city', models.CharField(blank=True, help_text='City or town', max_length=100)),
                ('country', models.CharField(blank=True, default='United Kingdom', help_text='Country', max_length=100)),
                ('photo', models.ImageField(default='student_photos/default.png', help_text='Student photo', upload_to='student_photos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, help_text='The course this student is enrolled in', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='auth.group')),
                ('user', models.OneToOneField(help_text='Linked user account', on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
