"""
Django settings for itapps project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!


# --- Environment Variable Detection ---
# WEBSITE_HOSTNAME is automatically set by Azure App Service
WEBSITE_HOSTNAME = os.environ.get("WEBSITE_HOSTNAME")

# --- DEBUG Setting ---
# Default to False in a cloud environment, True locally.
# The environment variable "DEBUG" on Azure can override this, but should be set to "False"
# in production App Settings to ensure security.
DEBUG = os.environ.get("DEBUG", "False").lower() == "true"

# If WEBSITE_HOSTNAME is present but no explicit DEBUG setting, default to production (False)
if WEBSITE_HOSTNAME and os.environ.get("DEBUG") is None:
    DEBUG = False
elif os.environ.get("DEBUG") is None:
    # If not on Azure and no explicit DEBUG setting, default to local/True
    DEBUG = True

# --- ALLOWED_HOSTS and CSRF Configuration ---
if DEBUG:
    # Development/Local Settings
    # Use ['*'] for maximum flexibility during local testing
    ALLOWED_HOSTS = ['*', '127.0.0.1', 'localhost']
    # CSRF_TRUSTED_ORIGINS defaults are usually sufficient for local development
    CSRF_TRUSTED_ORIGINS = [] 

else:
    # Production (Azure App Service) Settings
    host = WEBSITE_HOSTNAME or ""
    
    # 1. ALLOWED_HOSTS: Include the primary hostname and the general Azure wildcard
    ALLOWED_HOSTS = [
        host,
        f"{host}".lower(),
        ".azurewebsites.net", # Catches any appname.azurewebsites.net
    ]
    
    # 2. CSRF_TRUSTED_ORIGINS: Must include a fix for Azure's deep subdomains 
    # (like the staging/instance hostname that failed)
    CSRF_TRUSTED_ORIGINS = [
        f"https://{host}",
        f"https://*.azurewebsites.net", # Trusts appname.azurewebsites.net
        # CRITICAL FIX: Trusts deep subdomains used by Azure internal routing (e.g., [GUID].uksouth-01.azurewebsites.net)
        f"https://*.*.azurewebsites.net", 
    ]

# SECURITY WARNING: Ensure DEBUG is False in production!


# Security settings
SECRET_KEY = os.environ.get('SECRET_KEY', 'Sk1b1d1R1zz67')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'itreporting',
    'users.apps.UsersConfig',
    'crispy_forms',
    'crispy_bootstrap4',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'itapps.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'itapps.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases





# Database configuration
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('AZURE_DB_NAME'),
        'USER': os.environ.get('AZURE_DB_USER'),
        'PASSWORD': os.environ.get('AZURE_DB_PASSWORD'),
        'HOST': os.environ.get('AZURE_DB_HOST'),
        'PORT': os.environ.get('AZURE_DB_PORT', '3306'),
    }
}




# Password validations
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

#STATIC_URL = 'static/'

#MEDIA_URL = '/media/'
#MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

AZURE_SA_NAME = os.environ.get('AZURE_SA_NAME')
AZURE_SA_KEY = os.environ.get('AZURE_SA_KEY', default='') 
STORAGES = {
    "default": {
        "BACKEND": "storages.backends.azure_storage.AzureStorage",
            "OPTIONS": {
            "account_name": AZURE_SA_NAME,
            "account_key": AZURE_SA_KEY,
            "azure_container": "media",
            },
        },
    "staticfiles": {
        "BACKEND": "storages.backends.azure_storage.AzureStorage",
        "OPTIONS": {
            "account_name": AZURE_SA_NAME,
            "account_key": AZURE_SA_KEY,
            "azure_container": "static",
            },
        },
    }
STATIC_URL = f'https://{AZURE_SA_NAME}.blob.core.windows.net/static/'
MEDIA_URL = f'https://{AZURE_SA_NAME}.blob.core.windows.net/media/'
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CRISPY_ALLOWED_TEMPLATE_PACKS = 'bootstrap4'
CRISPY_TEMPLATE_PACK = 'bootstrap4'

LOGIN_REDIRECT_URL = 'itreporting:home'
LOGIN_URL = 'login'