# Generated by Django 5.2.7 on 2025-12-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('itreporting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the module', max_length=200)),
                ('code', models.CharField(help_text='Unique module code (e.g., 55-606366)', max_length=20, unique=True)),
                ('credit', models.IntegerField(default=20, help_text='Credit hours for this module')),
                ('category', models.CharField(choices=[('CORE', 'Core Module'), ('OPTIONAL', 'Optional Module'), ('ELECTIVE', 'Elective Module')], default='CORE', help_text='Category of the module', max_length=20)),
                ('description', models.TextField(help_text='Detailed description of the module')),
                ('availability', models.BooleanField(default=True, help_text='Is this module open for student registration?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courses_allowed', models.ManyToManyField(help_text='Which courses (Groups) are allowed to register for this module', related_name='modules', to='auth.group')),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
                'ordering': ['code'],
            },
        ),
        migrations.DeleteModel(
            name='Issue',
        ),
    ]
