# Generated by Django 5.2.7 on 2025-12-28 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itreporting', '0002_module_delete_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='code',
            field=models.CharField(help_text='Unique module code (e.g., 55-123456)', max_length=20, unique=True),
        ),
    ]
