# Generated by Django 5.2.7 on 2025-12-28 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itreporting', '0003_alter_module_code'),
        ('users', '0004_student_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='code',
            field=models.CharField(help_text='Unique module code (e.g., 55-606366)', max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_registered', models.DateTimeField(auto_now_add=True, help_text='When the student registered for this module')),
                ('module', models.ForeignKey(help_text='The module being registered for', on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='itreporting.module')),
                ('student', models.ForeignKey(help_text='The student who registered for this module', on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='users.student')),
            ],
            options={
                'verbose_name': 'Registration',
                'verbose_name_plural': 'Registrations',
                'ordering': ['-date_registered'],
                'unique_together': {('student', 'module')},
            },
        ),
    ]
